### ISSUE TITLE
test runner shells out to environment ruby rather than using current ruby

### ISSUE THREAD

**Issue by mattly** [tslocke/rubydoctest#1]
while attempting to run my doctests under ruby19, i discovered that the doctest runner shells out to whatever happens to be at "ruby", which may not be the current ruby environment that doctest is being run in.

Given that you're shelling out, I don't see a particularly obvious solution to this problem, but thought I should document it regardless.

**Comment by bryanlarsen** [comment]
Actually, it should be shelling out to `RUBY = File.join(Config::CONFIG['bindir'], Config::CONFIG['ruby_install_name']).sub(/.*\s.*/m, '"\&"')`

So it's not shelling out to the right ruby, you're running an old version of rubydoctest or your ruby configuration is broken somehow.   If it's the latter, I'd be interested in tracking it down.

**Comment by mattly** [comment]
I'm running 1.0.0, which is the latest version on gemcutter. 

nevertheless: http://gist.github.com/272686

**Comment by bryanlarsen** [comment]
yes, the real bug is that Tom is having trouble pushing to gemcutter.   If you build from source "rake gem", you won't have this problem.

**Comment by mattly** [comment]
ah, well that would make sense. Thanks, I'll give building the gem from source a go.

**Comment by mattly** [comment]
btw, any luck getting an official 1.0.1 out there? I'm sure @qrush would be happy to help, especially now that gemcutter/rubygems.org has an official help site now: http://help.rubygems.org/

**Comment by qrush** [comment]
Running through my open issues...is this still happening?

**Comment by mattly** [comment]
Closing because it's been nearly six years, I'm cleaning up old issues I'm subscribed to, and I haven't written ruby in a while.
