### ISSUE TITLE
Support expected exceptions

### ISSUE THREAD

**Issue by tfausak** [tslocke/rubydoctest#10]
Sometimes you want to show how your code can fail, meaning you want it to raise an exception. Python's doctest supports exceptions: https://docs.python.org/3.4/library/doctest.html#what-about-exceptions.

``` py
>>> 1 / 0
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ZeroDivisionError: integer division or modulo by zero
```

```
Trying:
    1 / 0
Expecting:
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    ZeroDivisionError: integer division or modulo by zero
ok
```

I cannot get a similar example to work using Ruby DocTest.

``` irb
>> 1 / 0
ZeroDivisionError: divided by 0
    from (irb):1:in `/'
    from (irb):1
    from /usr/bin/irb:12:in `<main>'
```

```
1.  ERR  | Default Test
           ZeroDivisionError: divided by 0
             from tmp/example.rb.txt:1
           1 / 0
```

**Comment by weakish** [comment]
In a verbose approach:

``` ruby
>> begin
 |   1 / 0
 | rescue ZeroDivisionError  
 |   'expected'
 | end  
=> "expected"
```

**Comment by tfausak** [comment]
While it is certainly possible to get this behavior with rubydoctest, I decided to make my own gem instead. You can read more about it here: http://taylor.fausak.me/2014/09/23/executable-documentation/

Since this issue hasn't had any movement for a year, I'll just close it.
