### ISSUE TITLE
Support ellipsis wildcards

### ISSUE THREAD

**Issue by tfausak** [tslocke/rubydoctest#9]
Python's doctest has an [ellipsis options](https://docs.python.org/3.4/library/doctest.html#doctest.ELLIPSIS). It's useful for removing parts of a test that aren't important or are known to change. For example, creating a new object:

``` py
>>> object() # doctest: +ELLIPSIS
<object object at 0x...>
```

```
Trying:
    object() # doctest: +ELLIPSIS
Expecting:
    <object object at 0x...>
ok
```

This test doesn't care what the actual memory address of the object is. As far as I can tell, there is no way to write a test like this with Ruby DocTest.

``` irb
>> Object.new
=> #<Object:0x...>
```

```
1.  FAIL | Default Test
           Got:      #<Object:0x007fc0b88c7c58>
           Expected: #<Object:0x...>
```

**Comment by tfausak** [comment]
It looks like [`normalize_result`](https://github.com/tablatom/rubydoctest/blob/9032ad2472524d281c3d5781133abb8e9527820d/lib/result.rb#L9-L11) is supposed to handle this, but it's hard coded to only allow 8 hex digits.

**Comment by weakish** [comment]
With some ugliness:

``` ruby
>> Object.new.to_s =~ /#<Object:0x.+>/
=> 0
```

**Comment by tfausak** [comment]
:point_right: https://github.com/tablatom/rubydoctest/issues/10#issuecomment-139545889
